name: nutriturk
description: "NutriTürk - Nihai Gıda Tarayıcı"

# Kodun Google Play'e gönderilmesini engeller, henüz hazır değiliz.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- ANA İŞLEVSELLİK PAKETLERİ ---
  
  # Kamera ile barkod taramak için
  mobile_scanner: ^5.1.0 

  # İnternetten veri çekmek için (OpenFoodFacts API)
  http: ^1.2.1

  # Cihazda ses dosyası çalmak için (başarı/hata sesi)
  audioplayers: ^6.0.0

  # Metni sese dönüştürmek için (ürün adını okuma)
  flutter_tts: ^4.0.2
  
  # URL açmak için (Destek ol linki vb.)
  url_launcher: ^6.2.6

  # --- ARAYÜZ PAKETLERİ ---

  # Google'ın Material Design ikonlarını kullanmak için
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Kod kalitesini yüksek tutmak için
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Resim dosyalarımızı (NutriScore, EcoScore vb.) ekleyeceğimiz yer
  # assets:
  #   - assets/images/
