# Bu iş akışının (workflow) adı
name: Build Flutter APK

# Bu iş akışı ne zaman tetiklenecek?
on:
  push:
    branches:
      - main # Sadece 'main' dalına bir kod gönderildiğinde çalış.

jobs:
  build:
    # Bu işin çalışacağı sanal makine tipi
    runs-on: ubuntu-latest

    steps:
      # 1. Adım: Kodlarımızı sanal makineye indir (checkout)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Adım: Java Geliştirme Kiti'ni (JDK) kur. Android için gereklidir.
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Adım: Flutter Geliştirme Kiti'ni (SDK) kur
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Flutter'ın kararlı (stable) versiyonunu kullan

      # 4. Adım: Projenin ihtiyaç duyduğu paketleri indir (pubspec.yaml'daki)
      - name: Get Flutter dependencies
        run: flutter pub get

      # 5. Adım: APK dosyasını oluştur!
      - name: Build APK
        run: flutter build apk --release

      # 6. Adım: Oluşturulan APK'yı bir "artifact" (ürün) olarak kaydet
      # Bu, APK'yı daha sonra indirebilmemiz için gereklidir.
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: nutriturk-apk # İndireceğimiz dosyanın adı
          path: build/app/outputs/flutter-apk/app-release.apk # APK'nın bulunduğu dosya yolu
